/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author fgdnv
 */
public class casu extends javax.swing.JFrame {

    /**
     * Creates new form casu
     */
    public casu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tf2 = new javax.swing.JComboBox<>();
        tf3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 330));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fgdnv\\Downloads\\go-back-icon.png")); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(19, 246, 80, 23);

        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf1FocusLost(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(95, 56, 99, 22);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\fgdnv\\Downloads\\Ok-icon.png")); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(181, 178, 72, 23);

        getContentPane().add(tf2);
        tf2.setBounds(95, 117, 99, 22);
        getContentPane().add(tf3);
        tf3.setBounds(243, 117, 90, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setText("      UPDATE   ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(243, 95, 90, 17);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("      REG NO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(95, 22, 99, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setText("     COURSE ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(95, 84, 99, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\fgdnv\\Downloads\\pngtree-modern-double-color-futuristic-neon-background-picture-image_1181573.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-3, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
cs m= new cs();
        m.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int  a=Integer.parseInt(tf1.getText());
        String b=tf2.getSelectedItem().toString();
         tf1.setText(null);
         String c=tf3.getText();
        // tf3.setText(null);
         
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","123");
            Statement st=con.createStatement();
            st.executeUpdate("update COURCEALLOCATIONSTUDENT   set COURSE_ID  = '"+c+"'  WHERE REGNO="+a+" and COURSE_ID LIKE '"+b+"'" );
JOptionPane.showMessageDialog(rootPane,"Update Successfull" );
        }
        catch(Exception e){
            System.out.println(e);

        }   
        tf3.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusLost
 int  a=Integer.parseInt(tf1.getText());
         try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","123");
            Statement st=con.createStatement();
             ResultSet rs=st.executeQuery("select * from COURCEALLOCATIONSTUDENT where REGNO="+a);
          //  cb.setModel(DbUtils.resultSetToTableModel(rs));
            while(rs.next()){
                tf2.addItem(rs.getString(1));
            }
  
           // JOptionPane.showMessageDialog(rootPane,"Update Successfull" );
        }
        catch(Exception e){
                System.out.println(e);
            
        } 
            // TODO add your handling code here:
    }//GEN-LAST:event_tf1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(casu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(casu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(casu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(casu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new casu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tf1;
    private javax.swing.JComboBox<String> tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
